// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaoCaoBaiTapLonNhom02.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230317092707_Cathi")]
    partial class Cathi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("BaoCaoBaiTapLonNhom02.Models.Cathi", b =>
                {
                    b.Property<string>("MaCathi")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThoigianCathi")
                        .HasColumnType("TEXT");

                    b.HasKey("MaCathi");

                    b.ToTable("Cathi");
                });

            modelBuilder.Entity("BaoCaoBaiTapLonNhom02.Models.Nhom", b =>
                {
                    b.Property<string>("MaNhom")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNhom")
                        .HasColumnType("TEXT");

                    b.HasKey("MaNhom");

                    b.ToTable("Nhom");
                });

            modelBuilder.Entity("BaoCaoBaiTapLonNhom02.Models.Student", b =>
                {
                    b.Property<string>("MaID")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaCathi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaNhom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaID");

                    b.HasIndex("MaCathi");

                    b.HasIndex("MaNhom");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("BaoCaoBaiTapLonNhom02.Models.Student", b =>
                {
                    b.HasOne("BaoCaoBaiTapLonNhom02.Models.Cathi", "Cathi")
                        .WithMany()
                        .HasForeignKey("MaCathi");

                    b.HasOne("BaoCaoBaiTapLonNhom02.Models.Nhom", "Nhom")
                        .WithMany()
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cathi");

                    b.Navigation("Nhom");
                });
#pragma warning restore 612, 618
        }
    }
}
